<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>Dreams of thought</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/theme/styles.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="/theme/slicknav.css">
    <script src="/theme/jquery.slicknav.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script type="text/javascript"
	    src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js"></script>
    <![endif]-->
<script>
	$(function(){
		$('#menu').slicknav({'label':''});
	});
</script>
<link rel="icon" href="/theme/favicon.ico" sizes="16x16 32x32 48x48 64x64" type="image/vnd.microsoft.icon">
<link rel="apple-touch-icon" sizes="114x114" href="/theme/apple-touch-icon-precomposed.png">
<link rel="apple-touch-icon" sizes="152x152" href="/theme/favicon152.png">
<link rel="apple-touch-icon" sizes="196x196" href="/theme/favicon196.png">
  </head>

  <body>
    <div id="wrapper">

      <header>
	<nav class="byline"><ul id="menu">
        </ul></nav><!-- /#menu -->
        <div class="downloads">
          <a href="#" class="fa fa-Twitter"></a>
          <a href="#" class="fa fa-Github"></a>
        </div>
        <hgroup>
          <h1>ForeignKey to custom user model in Django</h1>
  <footer class="article-footer">
    <address class="vcard author">
      By           <a class="url fn" href="./author/admin.html">admin</a>
    </address>
    <abbr class="published" title="2013-07-16T14:30:00+05:30">
       on 16.07.2013
    </abbr>
  </footer><!-- /.post-info -->
        </hgroup>
  



      </header>
<section id="content" class="body article">
  <div class="entry-content">
    <p>Came across this problem when running a syncdb in Django (&gt;=1.5) :
| `` CommandError: One or more models did not validate: APP.ModelName: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.``</p>
<p>So you define a custom user model and add the appropriate line to the
settings.py file. Then you add a ForeignKey from a model in your app the
way the <a class="reference external" href="https://docs.djangoproject.com/en/1.5/topics/auth/customizing/#django.contrib.auth.get_user_model">Django
doc</a>
tells you to. And then you see this (the one above) error when you run a
syncdb.</p>
<p>We hit upon this problem. The reason this happened was that the
AUTH_USER_MODEL setting was below the INSTALLED_APPS in the
settings.py file. Django will not handle forward referencing in this
case. The solution is to simply move the AUTH_USER_MODEL setting above
the INSTALLED_APPS settting.</p>

  </div><!-- /.entry-content -->
  <div class="article-share-tags">
  <div class="end-article-tags">
  </div>
  <div class='article-share'>
      share -
  </div>
  </div>
</section>
<div class="neighbors">
</div>
      <footer>
	  <a href="./pages/about.html" >About</a>
	  <div class="right-footer">
	  <a href="./categories.html" >Categories</a>
	  <a href="./tags.html" >Tags</a>
	  </div>
      </footer>
</body>
</html>